zackargyle/service-workers

packages/generate-service-worker/README.md, packages/generate-service-worker/utils/validate.js, packages/generate-service-worker/utils/validators.js, packages/service-worker-plugin/README.md
Support while offline is supported, but the docs were missing any explanation. Essentially, if you want to enable "offline" support, you should be using an App Shell for your html response, and set the `offline` option to true in caching. It's as simple as:
```js
const config = {
cache: {
offline: true
}
};
```
With `offline` set to true, the service worker will cache the HTML response for the page and use it in the case of an offline static route change.
=> Update docs for offline support

.gitignore, packages/generate-service-worker/templates/__tests__/cache.js, packages/service-worker-mock/README.md, packages/service-worker-mock/index.js, packages/service-worker-mock/models/Headers.js, packages/service-worker-mock/models/Request.js, packages/service-worker-mock/models/Response.js, packages/service-worker-mock/package.json, testing/fixtures.js
Fleshes out service-worker-mock with constructors needed by robust Service Workers, such as
```js
var url = new URL(request.url);
if (request.mode === 'cors' ||
['GET', 'HEAD', 'OPTIONS'].indexOf(request.method) < 0 ||
(url.protocol !== "http:" && url.protocol !== "https:")) {
console.log("s.w. not handling:", request.mode, request.method, url.href);
} else {
evt.respondWith(cacheOrNetwork(request));
}
```
=> service-worker-mock: adds stubs for Request & Response, and a real URL

packages/service-worker-mock/models/Cache.js
Api docs: https://developer.mozilla.org/en-US/docs/Web/API/Cache/keys
Current return type: MapIterator.
=> Fix: cache.keys() should return an array of keys

packages/service-worker-mock/models/Cache.js
[MatchAll specifications](https://developer.mozilla.org/en-US/docs/Web/API/Cache/matchAll) states that `it resolves with response[0] (i.e. the first matching response) instead of response (all matching response in an array)`. 
Here `response[0]` refers to `the first fetching record entry of its request to response map, in key insertion order`([reference](https://www.w3.org/TR/service-workers-1/#cache-matchall-method)) instead of "the earliest record that exists in this request-response map that matches this request". In another word, for each request, there will only be one response correspond to it, except when there exists requests with a ["VARY" header](https://developer.mozilla.org/en-US/docs/Web/API/Cache/keys) in its response.
Current implementation is not considering "VARY" …
=> Fix: Put now overwrites existing key-value pairs

packages/service-worker-mock/models/Cache.js
Fixes #40 
This changes the map store from storing url's and Response objects to storing url to a Response, Request pair.
This is then used to return the Request object as the key for cache entries and Response object for the value. This changes the current behavior of returning String's which isn't to spec.
=> Moving cache object over to using Requests

packages/service-worker-mock/index.js
This is a change to address #43. The change is to both add a `ServiceWorkerGlobalScope` class to the global scope, and to make sure that `self` is an instance of that class. This required no breaking changes because (fortunately) all class instance variables are iterable and are copied over with `Object.assign`. 
This does 2 things:
1. Adds `global.ServiceWorkerGlobalScope`.
2. Makes `global.self` the current instanceof `global.ServiceWorkerGlobalScope`.
=> Add ServiceWorkerGlobalScope mock

packages/service-worker-plugin/index.js
I'm having an issue with this plugin because of the way you register the service worker against the `publicPath` from WebPack...
In our case, we have the following in `output`...
```js
output: {
path: path.join(__dirname, "public", "assets"),
filename: "[name].js",
chunkFilename: "[name]_[chunkhash:20].js",
publicPath: `/assets/`,
libraryTarget: "var",
}
```
Since the `generateRuntime` file uses the `publicPath`, https://github.com/pinterest/service-workers/blob/master/packages/service-worker-plugin/utils/generateRuntime.js#L15, the "scope" of the service worker is incorrectly getting set to `http://localhost:3000/assets/` and isn't firing correctly.
I tried to pass `publicPath: "/"` directly into the options for this plugin, but that messed up the `precache` assets because they were …
=> fix: Support new scope option

.eslintrc.json, package.json, packages/generate-service-worker/templates/__tests__/cache.js, packages/service-worker-mock/__tests__/basic.js, packages/service-worker-mock/__tests__/makeServiceWorkerEnv.js, packages/service-worker-mock/index.js, packages/service-worker-mock/models/Cache.js, packages/service-worker-mock/models/FetchEvent.js, packages/service-worker-mock/models/Request.js, yarn.lock
This PR (based on #38) ended up being larger than expected :)
The main difference is that `location` is now an instance of URL. This required changes to `Request`, `FetchEvent` and `Cache`(for relative url matching), and required some updates to the tests that were not using url paths correctly.
It allows manually setting the location for the environment.
```
makeServiceWorkerEnv({ locationUrl, locationBase });
```
=> Update service-worker-mock to use a location URL

packages/service-worker-mock/models/FetchEvent.js, packages/service-worker-mock/utils/eventHandler.js
This PR updates FetchEvent to be inline with the [Spec](https://developer.mozilla.org/en-US/docs/Web/API/FetchEvent/FetchEvent). Original issue found here: #52.
=> Update service-worker-mock FetchEvent

packages/service-worker-mock/__tests__/makeServiceWorkerEnv.js, packages/service-worker-mock/index.js, packages/service-worker-mock/models/Cache.js, packages/service-worker-mock/models/CacheStorage.js, packages/service-worker-mock/models/Clients.js
This is a feature request from #62. It adds the ability to reset the environment.
```js
self.resetSwEnv();
self.listeners.reset();
self.caches.reset();
(await self.caches.open(key)).reset();
self.clients.reset();
```
=>  Update service-worker-mock to include reset methods

packages/service-worker-mock/index.js
Fixes #68 
This means that only Node 7+ will support the `searchParams` property of URL.
(I'm not aware of any other differences.)
=> Prefer the first-party WHATWG URL implementation when available.

packages/service-worker-mock/index.js, packages/service-worker-mock/models/MessageEvent.js, packages/service-worker-mock/utils/eventHandler.js
This adds a new `MessageEvent` model that is used to handle events of type `message`. These events can be triggered on a worker by using the workers `postMessage` API.
=> Handle 'message' events

packages/service-worker-mock/__tests__/Headers.js, packages/service-worker-mock/models/Headers.js
As per https://fetch.spec.whatwg.org/#dom-headers-get
(Related: https://github.com/GoogleChrome/workbox/pull/1422)
=> Headers.get() should return null when the header doesn't exist.

packages/service-worker-mock/package.json
Following the readme (`const makeFetchMock = require('service-worker-mock/fetch');`) would result in an error because the file was not published.
=> fix(service-workers-mock): fetch.js was not published

.eslintignore, packages/service-worker-mock/__tests__/FetchEvent.js, packages/service-worker-mock/models/FetchEvent.js
When using `service-worker-mock`, I found that triggering a fetch event with a string would fail with error: 
```
TypeError: Class constructor Request cannot be invoked without 'new'
```
This PR fixes the error.
* Fix triggering a fetch event with a string
* Triggering a `fetch` event with a string was not working properly because it was not calling the constructor with `new`
* Fixed eslint
* Lint was being called on the nested `node_modules` in `service-worker-mock`
=> Bugfix - fix triggering a fetch event with a string

packages/service-worker-mock/__tests__/ServiceWorkerGlobalScope.js, packages/service-worker-mock/models/Body.js, packages/service-worker-mock/models/Response.js
Making Response extend Body and using its resolver methods. The only backwards incompatible change is throwing for unsupported response types.
=> Response extends body

packages/service-worker-mock/utils/eventHandler.js
As title, mock notification closed event in service-worker-mock.
```
self.addEventListener('notificationclose', function(NotificationEvent) {
...
});
```
https://developer.mozilla.org/en-US/docs/Web/API/ServiceWorkerGlobalScope/onnotificationclose
=> Support "notificationclose" event in mock

packages/service-worker-mock/index.js, packages/service-worker-mock/models/Client.js, packages/service-worker-mock/models/Clients.js, packages/service-worker-mock/models/WindowClient.js
- Mock [`WindowClient`](https://developer.mozilla.org/en-US/docs/Web/API/WindowClient) which inherited from `Client` model.
- Clients's `openWindow()` method should append `WindowClient` into list, instead of `Client`.
=> Mock WindowClient interface

packages/service-worker-mock/__tests__/Headers.js, packages/service-worker-mock/models/Headers.js
Sets all header names to lowercase.
See: https://developer.mozilla.org/en-US/docs/Web/API/Headers/get
=> fix(service-worker-mock) Make header names case-insensitive

packages/service-worker-mock/__tests__/Response.js, packages/service-worker-mock/models/Body.js, packages/service-worker-mock/models/Response.js
- Adds `Response.error()`
- https://developer.mozilla.org/en-US/docs/Web/API/Response/error
=> feat(Response) Add `Response.error()`

packages/service-worker-mock/__tests__/NotificationEvent.js, packages/service-worker-mock/models/MessagePort.js, packages/service-worker-mock/models/NotificationEvent.js, packages/service-worker-mock/models/ServiceWorkerRegistration.js, packages/service-worker-mock/package.json, packages/service-worker-mock/utils/eventHandler.js
according to https://developer.mozilla.org/en-US/docs/Web/API/NotificationEvent `NotificationEvent` should have an `action` property. This should be backwards compatible with how it was before.
=> add action to NotificationEvent

packages/service-worker-plugin/index.js
`Tapable.plugin` is deprecated in webpack v4. Converted the plug-in to use hooks when they are available.
```
(node:1222) DeprecationWarning: Tapable.plugin is deprecated. Use new API on `.hooks` instead
at ProgressiveWebappPlugin.apply (/mnt/pinboard/webapp/node_modules/service-worker-plugin/index.js:26:12)
at webpack (/mnt/pinboard/webapp/node_modules/webpack/lib/webpack.js:47:13)
at Object.<anonymous> (/mnt/pinboard/webapp/startWebpackDevServer.js:10:16)
at Module._compile (module.js:653:30)
at Object.Module._extensions..js (module.js:664:10)
at Module.load (module.js:566:32)
at tryModuleLoad (module.js:506:12)
at Function.Module._load (module.js:498:3)
at Function.Module.runMain (module.js:694:10)
at startup (bootstrap_node.js:204:16)
at bootstrap_node.js:625:3
```
Similar PR: …
=> Fix webpack v4 deprecation warning

packages/service-worker-mock/__tests__/Response.js, packages/service-worker-mock/models/Response.js, testing/jest-setup.js
Fixes https://github.com/pinterest/service-workers/issues/119 and adds a mock implementation for [Response.redirect](https://developer.mozilla.org/en-US/docs/Web/API/Response/redirect).
=> add Response.redirect API

packages/service-worker-mock/__tests__/FetchEvent.js, packages/service-worker-mock/__tests__/basic.js, packages/service-worker-mock/models/FetchEvent.js, packages/service-worker-mock/utils/eventHandler.js
From #131 add possibility to pass a _clientId_ through the fetch trigger so that it will be available in the fetch event listeners.
=> Add clientId to fetch event (#131)

packages/service-worker-mock/README.md
In v2, `self.listeners` is a `Map` object, instead of a plain `object`. This change updates the readme to give examples that use this updated object, rather than the v1 method.
=> Update Readme to reflect changes to listeners map
